apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: broker-amq-mqtt
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acceptors:
    - expose: true
      name: all
      port: 61616
    - expose: true
      name: mqtt
      port: 1883
      protocols: mqtt
  adminPassword: admin
  adminUser: admin
  console:
    expose: true
  deploymentPlan:
    size: 1
    messageMigration: false
    managementRBACEnabled: true
    journalType: aio
    enableMetricsPlugin: true
  upgrades:
    enabled: false
    minor: false
